title: "Thomas Lee — Journal"
description: "Notes, ideas and stories."
url: "https://thomasjameslee1.github.io"
baseurl: "/journal"
markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: Australia/Sydney
plugins: []
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
